"""add dkim keys in domain

Revision ID: 087eb71589df
Revises: 1b548b82a1a9
Create Date: 2024-07-30 11:02:29.448038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087eb71589df'
down_revision: Union[str, None] = '1b548b82a1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('dkim_selector', sa.String(length=50), nullable=True))
    op.add_column('domains', sa.Column('dkim_private', sa.Text(), nullable=True))
    op.add_column('domains', sa.Column('dkim_public', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'dkim_public')
    op.drop_column('domains', 'dkim_private')
    op.drop_column('domains', 'dkim_selector')
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

