"""domains and senders

Revision ID: 0bbcac8d1a81
Revises: 8ffff45dc8a3
Create Date: 2024-07-24 12:43:23.922038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bbcac8d1a81'
down_revision: Union[str, None] = '8ffff45dc8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_domains',
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('alias_domain', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_alias_domains_alias_domain'), 'alias_domains', ['alias_domain'], unique=False)
    op.create_table('mailbox_domains',
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('mailbox_domain', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_mailbox_domains_mailbox_domain'), 'mailbox_domains', ['mailbox_domain'], unique=False)
    op.create_table('sender_login_map',
    sa.Column('sender', sa.String(length=256), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('sender', 'login')
    )
    op.create_index(op.f('ix_sender_login_map_domain'), 'sender_login_map', ['domain'], unique=False)
    op.create_index(op.f('ix_sender_login_map_login'), 'sender_login_map', ['login'], unique=False)
    op.alter_column('aliases', 'domain',
               existing_type=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliases', 'domain',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_sender_login_map_login'), table_name='sender_login_map')
    op.drop_index(op.f('ix_sender_login_map_domain'), table_name='sender_login_map')
    op.drop_table('sender_login_map')
    op.drop_index(op.f('ix_mailbox_domains_mailbox_domain'), table_name='mailbox_domains')
    op.drop_table('mailbox_domains')
    op.drop_index(op.f('ix_alias_domains_alias_domain'), table_name='alias_domains')
    op.drop_table('alias_domains')
    # ### end Alembic commands ###

