"""Add unique constraint user.uuid

Revision ID: 0d49a7816002
Revises: b867bc05ce80
Create Date: 2024-05-17 16:08:18.384721

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d49a7816002"
down_revision: Union[str, None] = "b867bc05ce80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("uuid", sa.String(length=64), nullable=True))
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=128), nullable=True)
    )
    op.create_unique_constraint("uuid_is_unique", "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uuid_is_unique", "users", type_="unique")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
