"""Add table for aliases

Revision ID: 8ffff45dc8a3
Revises: f490d32d35eb
Create Date: 2024-05-28 11:09:21.130857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffff45dc8a3'
down_revision: Union[str, None] = 'f490d32d35eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('alias', sa.String(length=500, collation='ascii_bin'), nullable=False),
    sa.Column('domain', sa.String(length=100, collation='ascii_bin'), nullable=False),
    sa.Column('destination', sa.String(length=500, collation='ascii_bin'), nullable=False),
    sa.PrimaryKeyConstraint('alias', 'destination')
    )
    op.create_index(op.f('ix_aliases_domain'), 'aliases', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aliases_domain'), table_name='aliases')
    op.drop_table('aliases')
    # ### end Alembic commands ###

