"""add errors

Revision ID: a00d7feb5df9
Revises: 7d80d2028a7f
Create Date: 2024-07-26 10:13:59.099634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00d7feb5df9'
down_revision: Union[str, None] = '7d80d2028a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('errors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'errors')
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

