"""add state and dates on domain

Revision ID: a836a69c1847
Revises: 0bbcac8d1a81
Create Date: 2024-07-24 17:41:12.707915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a836a69c1847'
down_revision: Union[str, None] = '0bbcac8d1a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'domains',
        sa.Column('state', sa.String(length=15), nullable=False)
    )
    op.add_column(
        'domains',
        sa.Column('dtcreated', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.add_column(
        'domains',
        sa.Column('dtupdated', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'dtupdated')
    op.drop_column('domains', 'dtcreated')
    op.drop_column('domains', 'state')
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliases', 'alias',
               existing_type=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=500),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('aliases', 'destination',
               existing_type=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=500),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade_postfix() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliases', 'destination',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=500),
               existing_nullable=False)
    op.alter_column('aliases', 'alias',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=500),
               existing_nullable=False)
    # ### end Alembic commands ###

