"""empty message

Revision ID: b867bc05ce80
Revises: 
Create Date: 2024-05-04 15:25:10.485667

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b867bc05ce80"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("name", sa.String(length=200, collation="ascii_bin"), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column(
            "webmail_domain",
            sa.String(length=200, collation="ascii_bin"),
            nullable=True,
        ),
        sa.Column(
            "mailbox_domain",
            sa.String(length=200, collation="ascii_bin"),
            nullable=True,
        ),
        sa.Column("imap_domains", sa.JSON(), nullable=True),
        sa.Column("smtp_domains", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("fullname", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "allowed",
        sa.Column("user", sa.String(length=32), nullable=False),
        sa.Column(
            "domain", sa.String(length=200, collation="ascii_bin"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["domain"],
            ["domains.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.name"],
        ),
        sa.PrimaryKeyConstraint("user", "domain"),
    )
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allowed")
    op.drop_table("users")
    op.drop_table("domains")
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "username", sa.String(length=128, collation="ascii_bin"), nullable=False
        ),
        sa.Column(
            "domain", sa.String(length=128, collation="ascii_bin"), nullable=False
        ),
        sa.Column(
            "password", sa.String(length=150, collation="ascii_bin"), nullable=False
        ),
        sa.Column("home", sa.String(length=255, collation="ascii_bin"), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("gid", sa.Integer(), nullable=False),
        sa.Column("active", mysql.CHAR(length=1), server_default="Y", nullable=False),
        sa.PrimaryKeyConstraint("username", "domain"),
    )
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
