"""fix column type

Revision ID: f490d32d35eb
Revises: 0d49a7816002
Create Date: 2024-05-17 17:36:53.322015

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f490d32d35eb"
down_revision: Union[str, None] = "0d49a7816002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_postfix() -> None:
    pass


def downgrade_postfix() -> None:
    pass


def upgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "uuid",
        existing_type=mysql.VARCHAR(length=64),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade_api() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "uuid",
        existing_type=sa.UUID(),
        type_=mysql.VARCHAR(length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def upgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dovecot() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
